// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlVGOJWwVA2MiAuaqiXAEwqa2TB8e1mKI',
    appId: '1:417308761583:web:923bea5d4b0edfb0e62a1a',
    messagingSenderId: '417308761583',
    projectId: 'my-mail-app-6b6a1',
    authDomain: 'my-mail-app-6b6a1.firebaseapp.com',
    storageBucket: 'my-mail-app-6b6a1.appspot.com',
    measurementId: 'G-G8RBCYT6EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1WBZ7xWcJwyW9avwS0sXhj8XhDZ_UkYI',
    appId: '1:417308761583:android:4a6a0080fd3125d8e62a1a',
    messagingSenderId: '417308761583',
    projectId: 'my-mail-app-6b6a1',
    storageBucket: 'my-mail-app-6b6a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ0SxsizOC9tCxcn8fR_D6x0sDvJ1IRxI',
    appId: '1:417308761583:ios:3aa955f4615d94cce62a1a',
    messagingSenderId: '417308761583',
    projectId: 'my-mail-app-6b6a1',
    storageBucket: 'my-mail-app-6b6a1.appspot.com',
    iosBundleId: 'com.example.11MailApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ0SxsizOC9tCxcn8fR_D6x0sDvJ1IRxI',
    appId: '1:417308761583:ios:3aa955f4615d94cce62a1a',
    messagingSenderId: '417308761583',
    projectId: 'my-mail-app-6b6a1',
    storageBucket: 'my-mail-app-6b6a1.appspot.com',
    iosBundleId: 'com.example.11MailApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlVGOJWwVA2MiAuaqiXAEwqa2TB8e1mKI',
    appId: '1:417308761583:web:3b375d3ac0383a8fe62a1a',
    messagingSenderId: '417308761583',
    projectId: 'my-mail-app-6b6a1',
    authDomain: 'my-mail-app-6b6a1.firebaseapp.com',
    storageBucket: 'my-mail-app-6b6a1.appspot.com',
    measurementId: 'G-LK41ELGHS4',
  );
}
